sunfishcode/c-ward

eyra/README.md

alternative is renaming the directory, to avoid repetition of `example`: `example-crates/eyra-example`

eyra readme: fix link to example

---

c-gull/Cargo.toml
c-scape/Cargo.toml
eyra/Cargo.toml

Eyra users may want to enable origin's log, env_logger, and experimental-relocate features, so make them available.

Expose the log, env_logger, and experimental-relocate options in eyra.

---

README.md
c-gull/Cargo.toml
eyra/README.md

Also, remove "log" from the default feature set, as it isn't needed to execute programs.

Add README.md documentation of the logging features.

---

README.md
c-gull/README.md
c-scape/build.rs
eyra/README.md

Add `#readme` anchors to repo URLs, capitalize Origin, and fix the comment in c-scape's build.rs to correctly describe the modes it's sensative too.

Miscellaneous documentation cleanups.

---

c-gull/Cargo.toml

Proc macros don't build under some RUSTFLAGS settings, and it turns out that tz-rs's use of proc macros is optional and we don't need it enabled, so disable them.

Disable default features of tz-rs, to avoid a proc macro dependency.

---

c-scape/Cargo.toml
example-crates/eyra-panic-example/.gitignore
example-crates/eyra-panic-example/Cargo.toml
example-crates/eyra-panic-example/README.md
example-crates/eyra-panic-example/build.rs
example-crates/eyra-panic-example/src/main.rs
tests/example_crates.rs

Have c-scape enable the unwinding resolver features that depend on libc, since c-scape provides libc. This includes `fde-phdr-dl`, which allows the Rust panic mechanism to work without any extra help.
And, add an example that does a panic and test that it works.

Enable the unwinding crate features needed to support Rust's panic.

---

c-scape/Cargo.toml
c-scape/src/io/mod.rs
c-scape/src/termios_/mod.rs

Use rustix-openpty to implement C-compatible ABIs for `openpty` and `login_tty`.

Implement `openpty` and `login_tty`.

---

c-gull/Cargo.toml
c-scape/Cargo.toml
example-crates/eyra-example/src/main.rs
example-crates/eyra-libc-example/Cargo.toml
example-crates/eyra-libc-example/src/main.rs
example-crates/eyra-optional-example/.gitignore
example-crates/eyra-optional-example/Cargo.toml
example-crates/eyra-optional-example/README.md
example-crates/eyra-optional-example/build.rs
example-crates/eyra-optional-example/src/main.rs
example-crates/eyra-panic-example/Cargo.toml
example-crates/eyra-panic-example/src/main.rs
eyra/Cargo.toml
eyra/README.md
eyra/src/lib.rs
tests/example_crates.rs

For users already using `libc`, it's inconvenient to add Eyra as a `libc` dependency, and for users not using `libc`, having Eyra be a passthrough isn't useful.
So instead, change the main instructions to use `extern crate eyra` instead of `extern crate libc`, and remove Eyra's `use libc::*;`. This makes it simpler overall, and easier to add Eyra to an existing codebase.
Also, add an example of adding Eyra as an optional dependency.

Stop having Eyra try to be a drop-in replacement for libc.

---

c-scape/src/process/wait.rs

Negative pid values mean to wait for process groups, however this isn't currently working in rustix. As a temporary workaround, have `waitpid` call `wait` in this situation.
When bytecodealliance/rustix#846 is released, we can use `waitpgid`, but until then, this workaround gets more things working.

Fix `waitpid`'s behavior on negative pid values.

---

eyra/README.md

Eyra can now run ripgrep, cargo-watch, bat, uutils coreutils, async-std, and tokio.

Add links to examples of popular Rust programs that run under Eyra.

---

c-gull/src/lib.rs
c-scape/src/fs/sendfile.rs
c-scape/src/lib.rs
c-scape/src/net/mod.rs

Implement get/sockopt support for `SO_TCP_USER_TIMEOUT`, `IPV6_RECVTCLASS`, and several others.
And add a simple implementation of `sendmsg` and `recvmsg`, that doesn't yet support ancillary messages, but can do basic data transfers.

Implement several more socket options, and `sendmsg` and `recvmsg`.

---

c-scape/src/fs/dir/readdir.rs
c-scape/src/lib.rs

We do depend on nightly for some unstable features, however it's nice to avoid doing that when we can.

Avoid depending on `#![feature(try_blocks)]`.

---

c-scape/src/fs/flock.rs
c-scape/src/fs/mod.rs
c-scape/src/fs/sync.rs
c-scape/src/process/rlimit.rs

rustix doesn't have `sync_file_range` yet, but `fdatasync` should suffice as a temporary measure.

Implement `flock`, `getrlimit`, and `sync_file_range`.

---

Cargo.toml
README.md
c-gull/Cargo.toml
c-gull/src/use_libc.rs
c-scape/Cargo.toml
c-scape/src/lib.rs
c-scape/src/use_libc.rs

- Exclude the "ci" directory from the published crate.
- Expose `atomic-dbg-logger` as a logging option.
- Tidy up comments.
- Improve rustc-dep-of-std mode.

Miscellaneous cleanups.

---

c-scape/src/mem/ntbs.rs
c-scape/src/thread/key.rs
c-scape/src/thread/mod.rs

I was doing some experiments with a modified version of libc-testsuite and found some miscellaneous bugs in strchr, strpbrk, strtok, pthread_setspecific, and pthread_cond_init.

Fix some bugs turned up in libc-testsuite.

---

README.md
c-gull/src/lib.rs
c-scape/src/lib.rs
example-crates/c-gull-lto/.gitignore
example-crates/c-gull-lto/Cargo.toml
example-crates/c-gull-lto/README.md
example-crates/c-gull-lto/build.rs
example-crates/c-gull-lto/src/main.rs
tests/example_crates.rs

`#![no_builtins]` [interferes with LTO], so stop using it. For `memcpy` etc., we'll just be careful to always call `compiler_builtins` instead of using plain code that could be pattern-matched.
If we ever want to stop using `compiler_builtins`, we can use [`black_box`] to prevent compilers from pattern-matching.
[interferes with LTO]: https://github.com/rust-lang/rust/blob/72e29da3eccd3e4c1fb2c581fa33216db50fcc93/compiler/rustc_codegen_ssa/src/back/link.rs#L1264
[`black_box`]: https://doc.rust-lang.org/stable/core/hint/fn.black_box.html

Fix LTO compatibility.

---

c-gull/src/resolve.rs
c-scape/src/glibc_versioning.rs
c-scape/src/process_.rs

This replaces manual NUL terminators.

Tidy up code to use `rustix::cstr`.

---

c-scape/src/lib.rs
example-crates/libc-replacement/src/main.rs
tests/example_crates.rs

When usingi libc, `origin::program::at_exit` is implemented in terms of `libc::atexit`, so don't have c-scape define `atexit` when in coexist-with-libc mode.

Don't define `exit`, `atexit`, etc. in coexist-with-libc mode.

---

c-gull/Cargo.toml
c-gull/README.md
c-gull/src/nss.rs
c-gull/src/resolve.rs
example-crates/dns/.gitignore
example-crates/dns/Cargo.toml
example-crates/dns/README.md
example-crates/dns/build.rs
example-crates/dns/src/main.rs
tests/example_crates.rs

Use the `getent ahosts` command to implement `getaddrinfo` instead of the sync-resolve crate, which is not actively maintained. This also follows the host DNS and NSS configuration.

Use `getent` for DNS resolution instead of sync-resolve.

---

c-gull/src/termios_.rs
c-gull/src/time.rs
c-scape/src/env/mod.rs
c-scape/src/fs/stat.rs
c-scape/src/fs/utime.rs
c-scape/src/io/read.rs
c-scape/src/lib.rs
c-scape/src/mem/mem.rs
c-scape/src/mem/ntbs.rs
c-scape/src/mm/mod.rs
c-scape/src/net/mod.rs
c-scape/src/process_.rs
c-scape/src/signal/mod.rs
c-scape/src/thread/key.rs
c-scape/src/time/mod.rs

Use `.cast` and `.cast_mut` to reduce `as` casting, and use `convert_res` to reduce manual errno code.

Miscellaneous code cleanups

---

c-gull/src/printf.rs
c-scape/Cargo.toml
c-scape/src/fs/memfd.rs
c-scape/src/fs/mod.rs
c-scape/src/lib.rs
c-scape/src/mem/chk.rs
c-scape/src/mm/mod.rs
c-scape/src/process/wait.rs
c-scape/src/process_.rs
c-scape/src/shm/mod.rs
c-scape/src/signal/mod.rs
c-scape/src/thread/mod.rs
c-scape/src/time/mod.rs

Fix several functions to better diagnose invalid argument values.
And implement mlockall, munlockall, __printf_chk, __sysconf, fpathconf, pathconf, shm_open, shm_unlink, sleep, usleep, memfd_create, and _SC_DELAYTIMER_MAX.

Fix several issues that I found running some POSIX conformance tests.

---

c-scape/src/errno_.rs
c-scape/src/process/kill.rs

This is a little tricky because glibc's strerror_r ABI uses a different return type than the standard `strerror_r`.

Implement `strerror_r.

---

c-scape/Cargo.toml
c-scape/src/thread/mod.rs

This requires updating the `create_thread` call to make the argument `Send`.

Update to origin 0.14.0.

---

c-scape/src/net/mod.rs
c-scape/src/process_.rs

Implement `SO_PEERCRED`, a few more `sysconf` codes, and `accept` taking a null destination address or getting an `AF_UNSPEC` address.
And add a special case for Unix-domain addresses where the caller has forgotten to add 1 for the NUL terminator to fix it up, so that rustix doesn't have to be aware of this.

Implement more features.

---

c-scape/src/fs/xattr.rs
c-scape/src/io/read.rs
c-scape/src/lib.rs
c-scape/src/net/mod.rs
c-scape/src/rand_.rs

Use thread-local static buffers for implementing `read` etc., instead of dynamically allocating a `Vec`. This allows them to be called in contexts where `malloc` isn't usable.

Use static buffers instead of `Vec`s for `read` etc.

---

c-scape/Cargo.toml
c-scape/src/thread/mod.rs

This updates to the new Origin `create_thread` API, which avoids the need for allocating a `Box` within `pthread_create`.

Update to origin 0.15.

---

c-scape/src/thread/key.rs
c-scape/src/thread/mod.rs
c-scape/src/todo.rs

Add error checking to `pthread_mutex_unlock`, `pthread_rwlock_unlock`, `pthread_getspecific`, and `pthread_setspecific`.

Implement `pthread_attr_getstacksize` and more error checking.

---

c-gull/Cargo.toml
c-scape/Cargo.toml
c-scape/src/at_fork.rs
c-scape/src/fs/readlink.rs
c-scape/src/process_.rs
c-scape/src/todo.rs

Update to rustix 0.38.22, with the new `fork` API, `readlinikat_raw`, and `sched_getcpu`.

Update to rustix 0.38.22.

---

c-gull/Cargo.toml
c-scape/Cargo.toml
c-scape/src/lib.rs
c-scape/src/mem/mem.rs
c-scape/src/mem/ntbs.rs

`compiler_builtins` is a very special crate, that needs `feature(rustc_private)`, that's installed along with rustc, and that appears to have some magic linking behavior, so in some situations it's desirable to avoid using it. Add an option to disable it, falling back to simple implementations.

Make use of `compiler_builtins` optional.

---

c-gull/Cargo.toml
c-scape/Cargo.toml

Instead of having c-gull define the "eyra" feature, define it in c-scape, and have c-gull depend on it. c-scape doesn't depend on std, so this will allow the eyra crate to offer a no-std mode which only depends on c-scape.

Add an "eyra" feature to c-scape, to better support no-std Eyra.

---

c-gull/src/use_libc.rs
c-scape/src/use_libc.rs

This macro works by using `transmute` to test for sizes at compile time, so it doesn't need to run the code.

Change the `checked_cast` macro to not execute the loads.

---

c-scape/Cargo.toml
c-scape/src/fs/dir/dirfd.rs
c-scape/src/fs/dir/mod.rs
c-scape/src/fs/dir/opendir.rs
c-scape/src/lib.rs
c-scape/src/pause.rs
c-scape/src/process/kill.rs
c-scape/src/signal/mod.rs
c-scape/src/todo.rs

- Implement `pause`, `__libc_current_sigrtmin`, `__libc_current_sigrtmax`
- Implement `sigpending`.
- Implement `sigsuspend`.
- Make `opendir` avoid opening a new file descriptor.

Implement several more functions, and make `opendir` avoid reopening the directory

---

c-gull/src/lib.rs
c-scape/src/exit.rs
c-scape/src/int.rs
c-scape/src/io/read.rs
c-scape/src/mem/chk.rs
c-scape/src/stdio.rs
c-scape/src/syscall.rs

Implement `__stack_chk_fail` and several more `*_chk` functions, as well as `__popcountdi2` and several integer functions.

Implement more "chk" functions and more integer operations.

---

c-scape/src/lib.rs
rust-toolchain.toml

This requires adding `#![feature(exposed_provenance)]`.

Update CI to the latest Rust nightly.

---

.github/workflows/main.yml
c-gull/src/system.rs
c-gull/src/use_libc.rs
c-scape/src/fs/makedev.rs
c-scape/src/path/mod.rs
c-scape/src/use_libc.rs

Fix errors in the `use_libc` modules that prevented `cargo test --workspace` from running, and add a few unit tests for it to run.

Make `cargo test --workspace` useful.

---

c-scape/src/syscall.rs

At the syscall level, Linux's `utimensat` can accept a null `path`, which tells it to behave like `futimens`. Implement this behavior in c-scape's `syscall` function.

When `utimensat` is invoked via `syscall`, emulate Linux behavior.

---

c-scape/src/mem/ntbs.rs
c-scape/src/todo.rs

This is a step towards a complete `strverscmp`: I was unsure how to use the libc macro so that still needs to be done, and stylistically seems quite different from some of the other code with more enums to try to match the C impl here https://codebrowser.dev/glibc/glibc/string/strverscmp.c.html#26 . Have not added any tests yet either . This was for issue https://github.com/sunfishcode/eyra/issues/34 in eyra

add strverscmp

---

c-scape/src/stdio.rs

In particular, this fixes writing `""`, when no bytes are written and it's not an error.

Fix `fputs` to detect errors properly.

---

c-scape/src/regex.rs
c-scape/src/stdio.rs
c-scape/src/strtol.rs

- Fix the return value of `strtol` with an invalid radix.
- Fix NUL-termination in `regerror`.
- Fix `sprintf` and `snprintf` NUL termination.

Fix some string-handling bugs

---

c-gull/src/system.rs
c-scape/src/path/mod.rs
c-scape/src/rand_.rs
c-scape/src/stdio.rs
c-scape/src/syscall.rs

Put test functions in `tests` modules, following common Rust conventions.

Testcase tidying.

---

c-scape/src/math/mod.rs
c-scape/src/mem/ntbs.rs
c-scape/src/todo.rs

This adds the functions described in https://man7.org/linux/man-pages/man3/isnanf.3.html for `f32` and `f64` removing `isnanf()` from todo.
Implemented are
- `finite`
- `finitef`
- `isnan`
- `isnanf`
- `isinf`
- `isinff`
and the missing maths functions
-`lgamma`
-`lgammaf`
It also cleans up `strcmp` and `strverscmp` such that the break conditions are in the while condition

Add finite and lgamma

---

c-scape/src/todo.rs

Sort todo.rs into a few categories, including one for all the functions that have rustix implementations together and just need C API wrappers.

Reorganize todo functions into a few categories.

---

c-scape/src/fs/fchown.rs
c-scape/src/fs/mod.rs
c-scape/src/fs/stat.rs
c-scape/src/termios_/mod.rs
c-scape/src/todo.rs

Adds implementations of 
-`fchownat` #113 
-`ptsname` #112 
-`ptsname_r`
-`fstatfs`
-`fstatfs64`
The static buffer for `ptsname` is 30 chars as in GLibC (https://codebrowser.dev/glibc/glibc/sysdeps/unix/sysv/linux/ptsname.c.html), as is the behaviour of returning a null pointer on error

Fchownat, ptsname and fstatfs

---

c-scape/src/process_.rs
c-scape/src/todo.rs
c-scape/src/todo/dl.rs

- Move `dl*` stubs into their own module.
- Move more functions that can be wrappers around `rustix` to their section in todo.rs
- Move `initgroups` to the NSS category.
- Move `if_*` functions to the NSS categorry.

Move todo function stub reorganization.

---

c-gull/Cargo.toml
c-scape/Cargo.toml
c-scape/src/fs/stat.rs

To handle negative timestamps, rustix now provides extension trait methods to access these fields.

Fix deprecation warnings on `st_mtime` etc.

---

c-gull/src/nss.rs
c-gull/src/resolve.rs
c-gull/src/system.rs
c-scape/src/glibc_versioning.rs
c-scape/src/mkostemps.rs
c-scape/src/path/mod.rs
c-scape/src/process/daemon.rs
c-scape/src/process/exec.rs
c-scape/src/process_.rs
c-scape/src/signal/mod.rs
c-scape/src/stdio.rs
c-scape/src/strtol.rs
c-scape/src/syscall.rs

Rust now has a C string literal syntax.

Switch from `rustix::cstr` to `c""` string literals.

---

c-scape/src/lib.rs

In coexist-with-libc mode, we don't control the layout of the `FILE` struct, so don't try to implement the stdio functions.

Don't define stdio functions in coexist-with-libc mode.

---

c-scape/src/stdio.rs

Fix errors and warnings in c-scape/src/stdio.rs when the "thread" feature is disabled.

Fix compile errors and warnings when "thread" is disabled.

---

README.md
c-gull/src/utmp.rs

- Don't panic if /var/run/utmp is missing
In a container as set up by Podman there is no utmp file in (/var)/run.
When no file is present, we can return NULL.
- Document requirements for runtime environment. (Based on the above this is only about `getent`.)

Don't panic if /var/run/utmp is missing

---

c-scape/Cargo.toml
c-scape/src/errno_.rs

This will help with integrating the musl dynamic linker until a rust replacement is written.
cc sunfishcode/origin#110

Use origin's errno_location in the __errno_location implementation

---

Cargo.toml
c-gull/src/nss.rs
c-gull/src/time.rs
c-scape/src/arpa_inet.rs
c-scape/src/base64.rs
c-scape/src/env/set.rs
c-scape/src/termios_/mod.rs
example-crates/c-gull-example/Cargo.toml
example-crates/c-gull-lto/Cargo.toml
example-crates/c-scape-example/Cargo.toml
example-crates/custom-allocator/Cargo.toml
example-crates/dns/Cargo.toml
example-crates/libc-replacement/Cargo.toml
example-crates/threadsafe-setenv/Cargo.toml
rust-toolchain.toml

Fix warnings about static mut variables, and remove the TODOs for the unwinding workaround.

Update to the latest Rust nightly.

---

c-gull/README.md
c-scape/README.md
c-scape/src/lib.rs

Document that c-scape and c-gull depend on Nightly Rust in the README.md files.
And add more documentation about "take-charge" and "coexist-with-libc" mode to c-scape's README.md.
Fixes #144.

Document that c-scape and c-gull depend on Nightly Rust.

---

README.md
c-scape/src/lib.rs

Add comments to c-scape's nightly features, sort the main `mod` list in lib.rs, and remove obsolete references to `compiler_builtins`.

Misc code cleanups.

---

c-scape/Cargo.toml

And revert #153, since cfg(panic = "unwind")` doesn't work in Cargo.toml.

Update to origin 0.23.3.

---

c-gull/src/lib.rs
c-scape/Cargo.toml
c-scape/src/jmp.rs
c-scape/src/lib.rs
rust-toolchain.toml

Update to origin 0.24 and the latest nightly Rust.

Update to the latest nightly Rust.
